version: "2"
services:
    prometheus:
        image: prom/prometheus:v2.37.6
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        ports:
            - '9090:9090'
    app:
        image: example2
        ports:
            - "5000:5000"
        depends_on:
            - prometheus
